require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FireworkCommentsController do

  # This should return the minimal set of attributes required to create a valid
  # FireworkComment. As you add validations to FireworkComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "comment" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FireworkCommentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all firework_comments as @firework_comments" do
      firework_comment = FireworkComment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:firework_comments).should eq([firework_comment])
    end
  end

  describe "GET show" do
    it "assigns the requested firework_comment as @firework_comment" do
      firework_comment = FireworkComment.create! valid_attributes
      get :show, {:id => firework_comment.to_param}, valid_session
      assigns(:firework_comment).should eq(firework_comment)
    end
  end

  describe "GET new" do
    it "assigns a new firework_comment as @firework_comment" do
      get :new, {}, valid_session
      assigns(:firework_comment).should be_a_new(FireworkComment)
    end
  end

  describe "GET edit" do
    it "assigns the requested firework_comment as @firework_comment" do
      firework_comment = FireworkComment.create! valid_attributes
      get :edit, {:id => firework_comment.to_param}, valid_session
      assigns(:firework_comment).should eq(firework_comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FireworkComment" do
        expect {
          post :create, {:firework_comment => valid_attributes}, valid_session
        }.to change(FireworkComment, :count).by(1)
      end

      it "assigns a newly created firework_comment as @firework_comment" do
        post :create, {:firework_comment => valid_attributes}, valid_session
        assigns(:firework_comment).should be_a(FireworkComment)
        assigns(:firework_comment).should be_persisted
      end

      it "redirects to the created firework_comment" do
        post :create, {:firework_comment => valid_attributes}, valid_session
        response.should redirect_to(FireworkComment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved firework_comment as @firework_comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        FireworkComment.any_instance.stub(:save).and_return(false)
        post :create, {:firework_comment => { "comment" => "invalid value" }}, valid_session
        assigns(:firework_comment).should be_a_new(FireworkComment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FireworkComment.any_instance.stub(:save).and_return(false)
        post :create, {:firework_comment => { "comment" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested firework_comment" do
        firework_comment = FireworkComment.create! valid_attributes
        # Assuming there are no other firework_comments in the database, this
        # specifies that the FireworkComment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FireworkComment.any_instance.should_receive(:update).with({ "comment" => "MyText" })
        put :update, {:id => firework_comment.to_param, :firework_comment => { "comment" => "MyText" }}, valid_session
      end

      it "assigns the requested firework_comment as @firework_comment" do
        firework_comment = FireworkComment.create! valid_attributes
        put :update, {:id => firework_comment.to_param, :firework_comment => valid_attributes}, valid_session
        assigns(:firework_comment).should eq(firework_comment)
      end

      it "redirects to the firework_comment" do
        firework_comment = FireworkComment.create! valid_attributes
        put :update, {:id => firework_comment.to_param, :firework_comment => valid_attributes}, valid_session
        response.should redirect_to(firework_comment)
      end
    end

    describe "with invalid params" do
      it "assigns the firework_comment as @firework_comment" do
        firework_comment = FireworkComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FireworkComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => firework_comment.to_param, :firework_comment => { "comment" => "invalid value" }}, valid_session
        assigns(:firework_comment).should eq(firework_comment)
      end

      it "re-renders the 'edit' template" do
        firework_comment = FireworkComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FireworkComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => firework_comment.to_param, :firework_comment => { "comment" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested firework_comment" do
      firework_comment = FireworkComment.create! valid_attributes
      expect {
        delete :destroy, {:id => firework_comment.to_param}, valid_session
      }.to change(FireworkComment, :count).by(-1)
    end

    it "redirects to the firework_comments list" do
      firework_comment = FireworkComment.create! valid_attributes
      delete :destroy, {:id => firework_comment.to_param}, valid_session
      response.should redirect_to(firework_comments_url)
    end
  end

end
