require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FireworkYearsController do

  # This should return the minimal set of attributes required to create a valid
  # FireworkYear. As you add validations to FireworkYear, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "year" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FireworkYearsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all firework_years as @firework_years" do
      firework_year = FireworkYear.create! valid_attributes
      get :index, {}, valid_session
      assigns(:firework_years).should eq([firework_year])
    end
  end

  describe "GET show" do
    it "assigns the requested firework_year as @firework_year" do
      firework_year = FireworkYear.create! valid_attributes
      get :show, {:id => firework_year.to_param}, valid_session
      assigns(:firework_year).should eq(firework_year)
    end
  end

  describe "GET new" do
    it "assigns a new firework_year as @firework_year" do
      get :new, {}, valid_session
      assigns(:firework_year).should be_a_new(FireworkYear)
    end
  end

  describe "GET edit" do
    it "assigns the requested firework_year as @firework_year" do
      firework_year = FireworkYear.create! valid_attributes
      get :edit, {:id => firework_year.to_param}, valid_session
      assigns(:firework_year).should eq(firework_year)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FireworkYear" do
        expect {
          post :create, {:firework_year => valid_attributes}, valid_session
        }.to change(FireworkYear, :count).by(1)
      end

      it "assigns a newly created firework_year as @firework_year" do
        post :create, {:firework_year => valid_attributes}, valid_session
        assigns(:firework_year).should be_a(FireworkYear)
        assigns(:firework_year).should be_persisted
      end

      it "redirects to the created firework_year" do
        post :create, {:firework_year => valid_attributes}, valid_session
        response.should redirect_to(FireworkYear.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved firework_year as @firework_year" do
        # Trigger the behavior that occurs when invalid params are submitted
        FireworkYear.any_instance.stub(:save).and_return(false)
        post :create, {:firework_year => { "year" => "invalid value" }}, valid_session
        assigns(:firework_year).should be_a_new(FireworkYear)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FireworkYear.any_instance.stub(:save).and_return(false)
        post :create, {:firework_year => { "year" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested firework_year" do
        firework_year = FireworkYear.create! valid_attributes
        # Assuming there are no other firework_years in the database, this
        # specifies that the FireworkYear created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FireworkYear.any_instance.should_receive(:update).with({ "year" => "1" })
        put :update, {:id => firework_year.to_param, :firework_year => { "year" => "1" }}, valid_session
      end

      it "assigns the requested firework_year as @firework_year" do
        firework_year = FireworkYear.create! valid_attributes
        put :update, {:id => firework_year.to_param, :firework_year => valid_attributes}, valid_session
        assigns(:firework_year).should eq(firework_year)
      end

      it "redirects to the firework_year" do
        firework_year = FireworkYear.create! valid_attributes
        put :update, {:id => firework_year.to_param, :firework_year => valid_attributes}, valid_session
        response.should redirect_to(firework_year)
      end
    end

    describe "with invalid params" do
      it "assigns the firework_year as @firework_year" do
        firework_year = FireworkYear.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FireworkYear.any_instance.stub(:save).and_return(false)
        put :update, {:id => firework_year.to_param, :firework_year => { "year" => "invalid value" }}, valid_session
        assigns(:firework_year).should eq(firework_year)
      end

      it "re-renders the 'edit' template" do
        firework_year = FireworkYear.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FireworkYear.any_instance.stub(:save).and_return(false)
        put :update, {:id => firework_year.to_param, :firework_year => { "year" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested firework_year" do
      firework_year = FireworkYear.create! valid_attributes
      expect {
        delete :destroy, {:id => firework_year.to_param}, valid_session
      }.to change(FireworkYear, :count).by(-1)
    end

    it "redirects to the firework_years list" do
      firework_year = FireworkYear.create! valid_attributes
      delete :destroy, {:id => firework_year.to_param}, valid_session
      response.should redirect_to(firework_years_url)
    end
  end

end
